
all: minmax.cc fairness.cc round.cc breakline.cc
	g++ -Wall -g -O2 minmax.cc -o minmax
	g++ -Wall -g -O2 fairness.cc -o fairness
	g++ -Wall -g -O2 round.cc -o round
	g++ -Wall -g -O2 breakline.cc -o breakline

clean:
	rm -f minmax fairness round breakline

